from app import app, db, Product, ensure_product_columns


def seed_products():
    with app.app_context():
        ensure_product_columns()
        # Clear existing data to prevent duplicates
        db.session.query(Product).delete()

        products = [
            # --- BEER (30) ---
            Product(name="Kingfisher Premium", price=150.0,
                    category="Beer", image_file="beer_kf_prem.jpg"),
            Product(name="Kingfisher Ultra", price=180.0,
                    category="Beer", image_file="beer_kf_ultra.jpg"),
            Product(name="Kingfisher Strong", price=140.0,
                    category="Beer", image_file="beer_kf_strong.jpg"),
            Product(name="Bira 91 White", price=170.0,
                    category="Beer", image_file="beer_bira_white.jpg"),
            Product(name="Bira 91 Blonde", price=160.0,
                    category="Beer", image_file="beer_bira_blonde.jpg"),
            Product(name="Bira 91 IPA", price=200.0,
                    category="Beer", image_file="beer_bira_ipa.jpg"),
            Product(name="Corona Extra", price=250.0,
                    category="Beer", image_file="beer_corona.jpg"),
            Product(name="Budweiser Premium", price=180.0,
                    category="Beer", image_file="beer_budweiser.jpg"),
            Product(name="Budweiser Magnum", price=220.0,
                    category="Beer", image_file="beer_budweiser_mag.jpg"),
            Product(name="Heineken Lager", price=200.0,
                    category="Beer", image_file="beer_heineken.jpg"),
            Product(name="Heineken Silver", price=190.0,
                    category="Beer", image_file="beer_heineken_sil.jpg"),
            Product(name="Carlsberg Smooth", price=160.0,
                    category="Beer", image_file="beer_carlsberg.jpg"),
            Product(name="Carlsberg Elephant", price=175.0,
                    category="Beer", image_file="beer_carlsberg_ele.jpg"),
            Product(name="Tuborg Green", price=150.0, category="Beer",
                    image_file="beer_tuborg_grn.jpg"),
            Product(name="Tuborg Strong", price=145.0,
                    category="Beer", image_file="beer_tuborg_str.jpg"),
            Product(name="Hoegaarden", price=350.0, category="Beer",
                    image_file="beer_hoegaarden.jpg"),
            Product(name="Stella Artois", price=320.0,
                    category="Beer", image_file="beer_stella.jpg"),
            Product(name="Guinness Draught", price=450.0,
                    category="Beer", image_file="beer_guinness.jpg"),
            Product(name="Asahi Super Dry", price=380.0,
                    category="Beer", image_file="beer_asahi.jpg"),
            Product(name="Tsingtao", price=300.0, category="Beer",
                    image_file="beer_tsingtao.jpg"),
            Product(name="Peroni", price=350.0, category="Beer",
                    image_file="beer_peroni.jpg"),
            Product(name="Leffe Blonde", price=400.0,
                    category="Beer", image_file="beer_leffe.jpg"),
            Product(name="Paulaner Weissbier", price=420.0,
                    category="Beer", image_file="beer_paulaner.jpg"),
            Product(name="Erdinger", price=430.0, category="Beer",
                    image_file="beer_erdinger.jpg"),
            Product(name="Beck's Ice", price=150.0,
                    category="Beer", image_file="beer_becks.jpg"),
            Product(name="Foster's", price=140.0, category="Beer",
                    image_file="beer_fosters.jpg"),
            Product(name="Haywards 5000", price=130.0,
                    category="Beer", image_file="beer_haywards.jpg"),
            Product(name="Knock Out", price=120.0, category="Beer",
                    image_file="beer_knockout.jpg"),
            Product(name="Miller High Life", price=160.0,
                    category="Beer", image_file="beer_miller.jpg"),
            Product(name="Amstel Light", price=170.0,
                    category="Beer", image_file="beer_amstel.jpg"),

            # --- RUM (30) ---
            Product(name="Old Monk Legend", price=1200.0,
                    category="Rum", image_file="rum_oldmonk.jpg"),
            Product(name="Bacardi Carta Blanca", price=1500.0,
                    category="Rum", image_file="rum_bacardi_w.jpg"),
            Product(name="Bacardi Black", price=1600.0,
                    category="Rum", image_file="rum_bacardi_b.jpg"),
            Product(name="Captain Morgan Spiced", price=1800.0,
                    category="Rum", image_file="rum_captain.jpg"),
            Product(name="Malibu Coconut", price=2200.0,
                    category="Rum", image_file="rum_malibu.jpg"),
            Product(name="Havana Club 3 Year", price=1900.0,
                    category="Rum", image_file="rum_havana3.jpg"),
            Product(name="Havana Club 7 Year", price=3200.0,
                    category="Rum", image_file="rum_havana7.jpg"),
            Product(name="Kraken Black Spiced", price=3500.0,
                    category="Rum", image_file="rum_kraken.jpg"),
            Product(name="Diplomatico Reserva", price=5500.0,
                    category="Rum", image_file="rum_diplomatico.jpg"),
            Product(name="Ron Zacapa 23", price=8500.0,
                    category="Rum", image_file="rum_zacapa.jpg"),
            Product(name="Appleton Estate", price=4200.0,
                    category="Rum", image_file="rum_appleton.jpg"),
            Product(name="Mount Gay Eclipse", price=3800.0,
                    category="Rum", image_file="rum_mountgay.jpg"),
            Product(name="Goslings Black Seal", price=4000.0,
                    category="Rum", image_file="rum_goslings.jpg"),
            Product(name="Cruzan Aged Dark", price=2500.0,
                    category="Rum", image_file="rum_cruzan.jpg"),
            Product(name="Plantation 3 Stars", price=3100.0,
                    category="Rum", image_file="rum_plantation.jpg"),
            Product(name="Brugal Anejo", price=2800.0,
                    category="Rum", image_file="rum_brugal.jpg"),
            Product(name="Flor de Cana 12", price=4500.0,
                    category="Rum", image_file="rum_flor.jpg"),
            Product(name="Don Q Cristal", price=2200.0,
                    category="Rum", image_file="rum_donq.jpg"),
            Product(name="Myers's Original", price=3000.0,
                    category="Rum", image_file="rum_myers.jpg"),
            Product(name="Pusser's British Navy", price=3800.0,
                    category="Rum", image_file="rum_pussers.jpg"),
            Product(name="Sailor Jerry", price=2900.0,
                    category="Rum", image_file="rum_sailor.jpg"),
            Product(name="Bumbu Original", price=5200.0,
                    category="Rum", image_file="rum_bumbu.jpg"),
            Product(name="El Dorado 12 Year", price=4800.0,
                    category="Rum", image_file="rum_eldorado.jpg"),
            Product(name="McDowell's No.1", price=800.0,
                    category="Rum", image_file="rum_mcdowells.jpg"),
            Product(name="Contessa Special", price=750.0,
                    category="Rum", image_file="rum_contessa.jpg"),
            Product(name="Hercules XXX", price=700.0,
                    category="Rum", image_file="rum_hercules.jpg"),
            Product(name="Khoday's XXX", price=850.0,
                    category="Rum", image_file="rum_khodays.jpg"),
            Product(name="Amrut Two Indies", price=1200.0,
                    category="Rum", image_file="rum_amrut.jpg"),
            Product(name="Maka Zai White", price=1100.0,
                    category="Rum", image_file="rum_makazai_w.jpg"),
            Product(name="Maka Zai Gold", price=1400.0,
                    category="Rum", image_file="rum_makazai_g.jpg"),

            # --- TEQUILA (30) ---
            Product(name="Jose Cuervo Especial Gold", price=3500.0,
                    category="Tequila", image_file="teq_cuervo_g.jpg"),
            Product(name="Jose Cuervo Silver", price=3400.0,
                    category="Tequila", image_file="teq_cuervo_s.jpg"),
            Product(name="Patron Silver", price=7500.0,
                    category="Tequila", image_file="teq_patron_s.jpg"),
            Product(name="Patron Reposado", price=8500.0,
                    category="Tequila", image_file="teq_patron_r.jpg"),
            Product(name="Don Julio Blanco", price=7000.0,
                    category="Tequila", image_file="teq_donjulio_b.jpg"),
            Product(name="Don Julio 1942", price=22000.0,
                    category="Tequila", image_file="teq_donjulio_1942.jpg"),
            Product(name="Herradura Silver", price=6500.0,
                    category="Tequila", image_file="teq_herradura.jpg"),
            Product(name="Espolon Blanco", price=4500.0,
                    category="Tequila", image_file="teq_espolon.jpg"),
            Product(name="Casamigos Blanco", price=8000.0,
                    category="Tequila", image_file="teq_casamigos.jpg"),
            Product(name="Clase Azul Reposado", price=30000.0,
                    category="Tequila", image_file="teq_claseazul.jpg"),
            Product(name="1800 Silver", price=5500.0,
                    category="Tequila", image_file="teq_1800.jpg"),
            Product(name="Sauza Silver", price=3200.0,
                    category="Tequila", image_file="teq_sauza.jpg"),
            Product(name="Hornitos Reposado", price=4800.0,
                    category="Tequila", image_file="teq_hornitos.jpg"),
            Product(name="El Jimador Blanco", price=3500.0,
                    category="Tequila", image_file="teq_jimador.jpg"),
            Product(name="Milagro Silver", price=4200.0,
                    category="Tequila", image_file="teq_milagro.jpg"),
            Product(name="Cabo Wabo Blanco", price=5000.0,
                    category="Tequila", image_file="teq_cabowabo.jpg"),
            Product(name="Avion Silver", price=5800.0,
                    category="Tequila", image_file="teq_avion.jpg"),
            Product(name="Tres Generaciones", price=6200.0,
                    category="Tequila", image_file="teq_tresgen.jpg"),
            Product(name="Cazadores Reposado", price=4500.0,
                    category="Tequila", image_file="teq_cazadores.jpg"),
            Product(name="Corralejo Reposado", price=5200.0,
                    category="Tequila", image_file="teq_corralejo.jpg"),
            Product(name="Ocho Plata", price=6500.0,
                    category="Tequila", image_file="teq_ocho.jpg"),
            Product(name="Fortaleza Blanco", price=7500.0,
                    category="Tequila", image_file="teq_fortaleza.jpg"),
            Product(name="Tapatio Blanco", price=4000.0,
                    category="Tequila", image_file="teq_tapatio.jpg"),
            Product(name="Gran Centenario", price=4800.0,
                    category="Tequila", image_file="teq_centenario.jpg"),
            Product(name="Maestro Dobel", price=7000.0,
                    category="Tequila", image_file="teq_dobel.jpg"),
            Product(name="Lunazul Blanco", price=3800.0,
                    category="Tequila", image_file="teq_lunazul.jpg"),
            Product(name="Olmeca Altos", price=3500.0,
                    category="Tequila", image_file="teq_olmeca.jpg"),
            Product(name="Teremana Blanco", price=6000.0,
                    category="Tequila", image_file="teq_teremana.jpg"),
            Product(name="Codigo 1530 Rosa", price=8500.0,
                    category="Tequila", image_file="teq_codigo.jpg"),
            Product(name="Desmond Ji 100% Agave", price=2500.0,
                    category="Tequila", image_file="teq_desmondji.jpg"),

            # --- VODKA (30) ---
            Product(name="Grey Goose", price=4500.0, category="Vodka",
                    image_file="vodka_greygoose.jpg"),
            Product(name="Absolut Original", price=2500.0,
                    category="Vodka", image_file="vodka_absolut.jpg"),
            Product(name="Smirnoff Red", price=1200.0,
                    category="Vodka", image_file="vodka_smirnoff.jpg"),
            Product(name="Belvedere", price=4800.0, category="Vodka",
                    image_file="vodka_belvedere.jpg"),
            Product(name="Tito's Handmade", price=3500.0,
                    category="Vodka", image_file="vodka_titos.jpg"),
            Product(name="Ketel One", price=3200.0, category="Vodka",
                    image_file="vodka_ketelone.jpg"),
            Product(name="Ciroc", price=4200.0, category="Vodka",
                    image_file="vodka_ciroc.jpg"),
            Product(name="Stolichnaya", price=2200.0,
                    category="Vodka", image_file="vodka_stoli.jpg"),
            Product(name="Skyy", price=2000.0, category="Vodka",
                    image_file="vodka_skyy.jpg"),
            Product(name="Finlandia", price=2100.0, category="Vodka",
                    image_file="vodka_finlandia.jpg"),
            Product(name="Russian Standard", price=2400.0,
                    category="Vodka", image_file="vodka_rs.jpg"),
            Product(name="Reyka", price=3800.0, category="Vodka",
                    image_file="vodka_reyka.jpg"),
            Product(name="Crystal Head", price=6500.0,
                    category="Vodka", image_file="vodka_crystal.jpg"),
            Product(name="Chopin Potato", price=5500.0,
                    category="Vodka", image_file="vodka_chopin.jpg"),
            Product(name="Beluga Noble", price=5200.0,
                    category="Vodka", image_file="vodka_beluga.jpg"),
            Product(name="Zubrowka Bison Grass", price=2800.0,
                    category="Vodka", image_file="vodka_zubrowka.jpg"),
            Product(name="Pinnacle", price=1800.0, category="Vodka",
                    image_file="vodka_pinnacle.jpg"),
            Product(name="Svedka", price=1900.0, category="Vodka",
                    image_file="vodka_svedka.jpg"),
            Product(name="Three Olives", price=2600.0,
                    category="Vodka", image_file="vodka_threeolives.jpg"),
            Product(name="Luksusowa", price=2300.0, category="Vodka",
                    image_file="vodka_luksusowa.jpg"),
            Product(name="Magic Moments", price=850.0,
                    category="Vodka", image_file="vodka_magic.jpg"),
            Product(name="Romanov", price=750.0, category="Vodka",
                    image_file="vodka_romanov.jpg"),
            Product(name="White Mischief", price=700.0,
                    category="Vodka", image_file="vodka_whitemischief.jpg"),
            Product(name="Eristoff", price=1100.0, category="Vodka",
                    image_file="vodka_eristoff.jpg"),
            Product(name="Wodka Gorbatschow", price=1000.0,
                    category="Vodka", image_file="vodka_gorba.jpg"),
            Product(name="Vladivar", price=900.0, category="Vodka",
                    image_file="vodka_vladivar.jpg"),
            Product(name="Fuel", price=950.0, category="Vodka",
                    image_file="vodka_fuel.jpg"),
            Product(name="Artic", price=1300.0, category="Vodka",
                    image_file="vodka_artic.jpg"),
            Product(name="Smoke Premium", price=2500.0,
                    category="Vodka", image_file="vodka_smoke.jpg"),
            Product(name="Khortytsa", price=2100.0, category="Vodka",
                    image_file="vodka_khortytsa.jpg"),

            # --- GIN (30) ---
            Product(name="Bombay Sapphire", price=3500.0,
                    category="Gin", image_file="gin_bombay.jpg"),
            Product(name="Tanqueray London Dry", price=3200.0,
                    category="Gin", image_file="gin_tanqueray.jpg"),
            Product(name="Hendrick's", price=4800.0,
                    category="Gin", image_file="gin_hendricks.jpg"),
            Product(name="Beefeater", price=2500.0, category="Gin",
                    image_file="gin_beefeater.jpg"),
            Product(name="Gordon's London Dry", price=2200.0,
                    category="Gin", image_file="gin_gordons.jpg"),
            Product(name="Roku", price=4500.0, category="Gin",
                    image_file="gin_roku.jpg"),
            Product(name="Monkey 47", price=6500.0,
                    category="Gin", image_file="gin_monkey47.jpg"),
            Product(name="Plymouth Gin", price=4200.0,
                    category="Gin", image_file="gin_plymouth.jpg"),
            Product(name="The Botanist", price=5500.0,
                    category="Gin", image_file="gin_botanist.jpg"),
            Product(name="Aviation", price=4000.0, category="Gin",
                    image_file="gin_aviation.jpg"),
            Product(name="Sipsmith", price=5000.0, category="Gin",
                    image_file="gin_sipsmith.jpg"),
            Product(name="Martin Miller's", price=4800.0,
                    category="Gin", image_file="gin_martin.jpg"),
            Product(name="Malfy Con Limone", price=4500.0,
                    category="Gin", image_file="gin_malfy.jpg"),
            Product(name="Opihr Spiced", price=3800.0,
                    category="Gin", image_file="gin_opihr.jpg"),
            Product(name="Hayman's Old Tom", price=3500.0,
                    category="Gin", image_file="gin_haymans.jpg"),
            Product(name="Boodles British", price=3400.0,
                    category="Gin", image_file="gin_boodles.jpg"),
            Product(name="Brockmans", price=5200.0, category="Gin",
                    image_file="gin_brockmans.jpg"),
            Product(name="Gin Mare", price=6000.0,
                    category="Gin", image_file="gin_mare.jpg"),
            Product(name="Nolet's Silver", price=7500.0,
                    category="Gin", image_file="gin_nolets.jpg"),
            Product(name="Empress 1908", price=6500.0,
                    category="Gin", image_file="gin_empress.jpg"),
            Product(name="Greater Than", price=1200.0,
                    category="Gin", image_file="gin_greaterthan.jpg"),
            Product(name="Hapusa Himalayan", price=2800.0,
                    category="Gin", image_file="gin_hapusa.jpg"),
            Product(name="Stranger & Sons", price=2200.0,
                    category="Gin", image_file="gin_stranger.jpg"),
            Product(name="Jaisalmer Craft", price=3500.0,
                    category="Gin", image_file="gin_jaisalmer.jpg"),
            Product(name="Terai India Dry", price=2500.0,
                    category="Gin", image_file="gin_terai.jpg"),
            Product(name="Samsara", price=2400.0, category="Gin",
                    image_file="gin_samsara.jpg"),
            Product(name="Tickle", price=1500.0, category="Gin",
                    image_file="gin_tickle.jpg"),
            Product(name="Pumori", price=2800.0, category="Gin",
                    image_file="gin_pumori.jpg"),
            Product(name="Trading Tides", price=3200.0,
                    category="Gin", image_file="gin_trading.jpg"),
            Product(name="Blue Riband", price=800.0, category="Gin",
                    image_file="gin_blueriband.jpg"),

            # --- COGNAC (30) ---
            Product(name="Hennessy V.S", price=6500.0,
                    category="Cognac", image_file="cog_hennessy_vs.jpg"),
            Product(name="Hennessy V.S.O.P", price=9500.0,
                    category="Cognac", image_file="cog_hennessy_vsop.jpg"),
            Product(name="Hennessy X.O", price=22000.0,
                    category="Cognac", image_file="cog_hennessy_xo.jpg"),
            Product(name="Remy Martin V.S.O.P", price=7200.0,
                    category="Cognac", image_file="cog_remy_vsop.jpg"),
            Product(name="Remy Martin X.O", price=24000.0,
                    category="Cognac", image_file="cog_remy_xo.jpg"),
            Product(name="Courvoisier V.S", price=5800.0,
                    category="Cognac", image_file="cog_courvoisier_vs.jpg"),
            Product(name="Courvoisier V.S.O.P", price=8000.0,
                    category="Cognac", image_file="cog_courvoisier_vsop.jpg"),
            Product(name="Martell V.S", price=6000.0,
                    category="Cognac", image_file="cog_martell_vs.jpg"),
            Product(name="Martell Cordon Bleu", price=18000.0,
                    category="Cognac", image_file="cog_martell_cb.jpg"),
            Product(name="Camus V.S.O.P", price=7500.0,
                    category="Cognac", image_file="cog_camus.jpg"),
            Product(name="Hine Rare V.S.O.P", price=8500.0,
                    category="Cognac", image_file="cog_hine.jpg"),
            Product(name="Meukow V.S", price=5500.0,
                    category="Cognac", image_file="cog_meukow.jpg"),
            Product(name="Pierre Ferrand 1840", price=7000.0,
                    category="Cognac", image_file="cog_pierre.jpg"),
            Product(name="Frapin V.S.O.P", price=8200.0,
                    category="Cognac", image_file="cog_frapin.jpg"),
            Product(name="Delamain Pale & Dry", price=12000.0,
                    category="Cognac", image_file="cog_delamain.jpg"),
            Product(name="Hardy V.S.O.P", price=7800.0,
                    category="Cognac", image_file="cog_hardy.jpg"),
            Product(name="Kelt V.S.O.P", price=9000.0,
                    category="Cognac", image_file="cog_kelt.jpg"),
            Product(name="D'Usse V.S.O.P", price=8800.0,
                    category="Cognac", image_file="cog_dusse.jpg"),
            Product(name="Bisquit & Dubouche", price=6800.0,
                    category="Cognac", image_file="cog_bisquit.jpg"),
            Product(name="Godet V.S", price=5200.0,
                    category="Cognac", image_file="cog_godet.jpg"),
            Product(name="ABK6 V.S.O.P", price=7600.0,
                    category="Cognac", image_file="cog_abk6.jpg"),
            Product(name="Gautier V.S", price=5400.0,
                    category="Cognac", image_file="cog_gautier.jpg"),
            Product(name="Braastad V.S.O.P", price=6500.0,
                    category="Cognac", image_file="cog_braastad.jpg"),
            Product(name="De Luze V.S.O.P", price=7200.0,
                    category="Cognac", image_file="cog_deluze.jpg"),
            Product(name="Louis Royer V.S.O.P", price=6900.0,
                    category="Cognac", image_file="cog_royer.jpg"),
            Product(name="Mansion House", price=1200.0,
                    category="Cognac", image_file="cog_mansionhouse.jpg"),
            Product(name="Honey Bee", price=900.0, category="Cognac",
                    image_file="cog_honeybee.jpg"),
            Product(name="Morpheus X.O Blended", price=1800.0,
                    category="Cognac", image_file="cog_morpheus.jpg"),
            Product(name="Kyron Premium", price=1500.0,
                    category="Cognac", image_file="cog_kyron.jpg"),
            Product(name="Good Earth", price=1400.0,
                    category="Cognac", image_file="cog_goodearth.jpg"),

            # --- WINE (30) ---
            Product(name="Jacob's Creek Shiraz", price=1800.0,
                    category="Wine", image_file="wine_jacobs_shiraz.jpg"),
            Product(name="Jacob's Creek Chardonnay", price=1800.0,
                    category="Wine", image_file="wine_jacobs_char.jpg"),
            Product(name="Sula Chenin Blanc", price=850.0,
                    category="Wine", image_file="wine_sula_chenin.jpg"),
            Product(name="Sula Cabernet Shiraz", price=950.0,
                    category="Wine", image_file="wine_sula_cab.jpg"),
            Product(name="Sula Dindori Reserve", price=1400.0,
                    category="Wine", image_file="wine_sula_dindori.jpg"),
            Product(name="Fratelli Sangiovese", price=1100.0,
                    category="Wine", image_file="wine_fratelli_san.jpg"),
            Product(name="Fratelli Classic Merlot", price=900.0,
                    category="Wine", image_file="wine_fratelli_mer.jpg"),
            Product(name="Grover La Reserve", price=1250.0,
                    category="Wine", image_file="wine_grover_la.jpg"),
            Product(name="Grover Art Collection", price=850.0,
                    category="Wine", image_file="wine_grover_art.jpg"),
            Product(name="Yellow Tail Merlot", price=1600.0,
                    category="Wine", image_file="wine_yellowtail_mer.jpg"),
            Product(name="Yellow Tail Shiraz", price=1600.0,
                    category="Wine", image_file="wine_yellowtail_shi.jpg"),
            Product(name="Moet & Chandon Brut", price=8500.0,
                    category="Wine", image_file="wine_moet.jpg"),
            Product(name="Dom Perignon Vintage", price=25000.0,
                    category="Wine", image_file="wine_dom.jpg"),
            Product(name="Veuve Clicquot", price=9500.0,
                    category="Wine", image_file="wine_veuve.jpg"),
            Product(name="Barefoot Moscato", price=1500.0,
                    category="Wine", image_file="wine_barefoot.jpg"),
            Product(name="Robert Mondavi Napa", price=4500.0,
                    category="Wine", image_file="wine_mondavi.jpg"),
            Product(name="Penfolds Koonunga Hill", price=2800.0,
                    category="Wine", image_file="wine_penfolds.jpg"),
            Product(name="Ruffino Chianti", price=2200.0,
                    category="Wine", image_file="wine_ruffino.jpg"),
            Product(name="Kendall-Jackson Vintner", price=3200.0,
                    category="Wine", image_file="wine_kendall.jpg"),
            Product(name="Chateau Ste. Michelle", price=2500.0,
                    category="Wine", image_file="wine_chateau.jpg"),
            Product(name="Beringer Zinfandel", price=1900.0,
                    category="Wine", image_file="wine_beringer.jpg"),
            Product(name="Lindeman's Bin 65", price=1400.0,
                    category="Wine", image_file="wine_lindemans.jpg"),
            Product(name="Carlo Rossi Red", price=1200.0,
                    category="Wine", image_file="wine_carlo.jpg"),
            Product(name="Brancott Estate", price=2100.0,
                    category="Wine", image_file="wine_brancott.jpg"),
            Product(name="Cote des Roses", price=2600.0,
                    category="Wine", image_file="wine_cote.jpg"),
            Product(name="York Arros", price=1500.0,
                    category="Wine", image_file="wine_york.jpg"),
            Product(name="Big Banyan Merlot", price=950.0,
                    category="Wine", image_file="wine_banyan.jpg"),
            Product(name="Krsma Syrah", price=2200.0,
                    category="Wine", image_file="wine_krsma.jpg"),
            Product(name="Soma Sauvignon Blanc", price=1100.0,
                    category="Wine", image_file="wine_soma.jpg"),
            Product(name="Chandon Brut (India)", price=1800.0,
                    category="Wine", image_file="wine_chandon_ind.jpg")
        ]

        default_abv_by_category = {
            "Beer": 5.0,
            "Wine": 13.5,
            "Rum": 42.8,
            "Tequila": 40.0,
            "Vodka": 40.0,
            "Gin": 42.8,
            "Cognac": 40.0
        }

        for product in products:
            product.quantity = 50
            product.alcohol_percentage = default_abv_by_category.get(
                product.category, 40.0
            )

        db.session.add_all(products)
        db.session.commit()
        print("Success: Database populated with 210 Premium products!")


if __name__ == '__main__':
    seed_products()
